package com.erhan.alex

import android.content.Context
import android.util.Log
import androidx.lifecycle.LiveData
import com.google.firebase.auth.FirebaseAuth
import java.io.File

private const val TAG = "EntryRepository"

class EntryRepository(private val entryDao: EntryDao, context: Context) {
    private val appContext = context.applicationContext
    val allEntries: LiveData<List<Entry>> = entryDao.getAll()

    private fun imageFile(uuid: String): File =
        File(appContext.filesDir, "images").resolve("IMG_$uuid.jpg")

    // ---- Local writes, each mirrored to the cloud (no-op when signed out) ----

    fun insert(entry: Entry) {
        entryDao.insertAll(entry)
        pushTracked(entry)
    }

    /**
     * Pushes an entry and its image, recording it as pending until the cloud confirms.
     * Marked *before* the attempt so that a push which no-ops (signed out) or fails is still
     * on [PendingPushes] for [reconcile] to drain, instead of disappearing without trace.
     */
    private fun pushTracked(entry: Entry) {
        PendingPushes.mark(appContext, entry.uuid)
        CloudSyncRepository.pushEntry(entry) { landed ->
            if (landed) PendingPushes.clear(appContext, entry.uuid)
        }
        CloudSyncRepository.pushImage(entry.uuid, imageFile(entry.uuid))
    }

    fun update(id: Int, uuid: String, newName: String, newWhere: String, newKind: String, newNotes: String, newDate: String) {
        val now = System.currentTimeMillis()
        entryDao.update(id, newName, newWhere, newKind, newNotes, newDate, now)
        // pushTracked also re-pushes the image, in case the photo was changed during the edit.
        pushTracked(
            Entry(
                id = id,
                name = newName,
                bwhere = newWhere,
                kind = newKind,
                date = newDate,
                notes = newNotes,
                pic = 0, // not sent to Firestore
                uuid = uuid,
                updatedAt = now
            )
        )
    }

    fun delete(id: Int, uuid: String) {
        imageFile(uuid).delete()
        entryDao.delete(id)
        // Nothing left to push; a lingering pending marker would keep the indicator stuck.
        PendingPushes.clear(appContext, uuid)
        CloudSyncRepository.deleteEntry(uuid)
    }

    // ---- Sign-in bootstrap / restore / reconcile ----

    /**
     * Run at every app start. The initial-sync flag used to be set only by the interactive Sign
     * In tap, so a session restored at launch left [reconcile] permanently disabled — the one
     * mechanism that re-pushes entries whose write never landed. A restored session is now
     * treated exactly like a fresh sign-in: bootstrap once, reconcile from then on.
     */
    suspend fun onAppStart() {
        PendingPushes.refresh(appContext)
        if (FirebaseAuth.getInstance().currentUser == null) return
        if (isInitialSyncDone()) reconcile() else onSignedIn()
    }

    /**
     * First action after a successful sign-in. If Room is empty this is a fresh
     * install/new device -> pull everything down. Otherwise this is the first cloud
     * enablement on an existing install -> push all local data up. Never blindly
     * pulls over existing local data.
     */
    suspend fun onSignedIn() {
        if (entryDao.getCount() == 0) {
            restoreFromCloud()
        } else {
            bootstrapPushAll()
        }
        markInitialSyncDone()
    }

    /** Pull all remote entries + images into Room / internal storage. */
    suspend fun restoreFromCloud() {
        // Firestore returns docs in document-id (= uuid) order, i.e. arbitrary. Insert oldest
        // first instead, so the autogenerated ids ascend with creation order the way they do on
        // the originating device — the list's same-day tiebreak (Adapter.setEntries) reads them.
        val remote = CloudSyncRepository.fetchAllRemoteEntries().sortedWith(
            compareBy(
                { (_, fields) -> sortableDateOrEmpty(fields["date"] as? String) },
                { (_, fields) -> fields["updatedAt"] as? Long ?: 0L }
            )
        )
        for ((uuid, fields) in remote) {
            entryDao.upsert(entryFromFields(uuid, fields))
            CloudSyncRepository.downloadImage(uuid, imageFile(uuid))
        }
    }

    /** Push every local entry + image up to the cloud (fire-and-forget per item). */
    private suspend fun bootstrapPushAll() {
        for (entry in entryDao.getAllOnce()) {
            pushTracked(entry)
        }
    }

    /**
     * Three-way reconciliation, run at app start once the initial sync has completed.
     * Handles deletions/failed-pushes that the fire-and-forget model can't retry inline.
     */
    suspend fun reconcile() {
        if (!isInitialSyncDone()) return

        val local = entryDao.getAllUuidTimestamps().associate { it.uuid to it.updatedAt }
        val remote = CloudSyncRepository.fetchAllRemoteEntries()
        val remoteTimestamps = remote.associate { (uuid, fields) ->
            uuid to (fields["updatedAt"] as? Long ?: 0L)
        }

        // Remote-only -> deleted locally while offline -> delete remote.
        //
        // Guarded, because this branch reads "the cloud has entries the phone doesn't" and the
        // far more likely cause of that is a broken local copy — cleared app data, a database
        // that failed to open, a restore that didn't finish — not the user deleting things while
        // offline. In those states the cloud is the *only* surviving copy, and deleting it is
        // unrecoverable. Genuine offline deletes are a handful of entries at a time, so refusing
        // an empty-local or bulk delete costs nothing: an in-app delete still calls
        // CloudSyncRepository.deleteEntry directly and takes effect immediately.
        val staleRemote = remoteTimestamps.keys - local.keys
        if (staleRemote.isNotEmpty()) {
            if (local.isNotEmpty() && staleRemote.size * 2 <= remoteTimestamps.size) {
                for (uuid in staleRemote) {
                    CloudSyncRepository.deleteEntry(uuid)
                }
            } else {
                Log.w(
                    TAG,
                    "Refusing to delete ${staleRemote.size}/${remoteTimestamps.size} remote " +
                        "entries: local holds only ${local.size}. Local copy looks damaged."
                )
            }
        }

        // Anything the remote has never seen, plus anything still marked pending from a push
        // that no-op'd or failed (an edit that never landed is pending but not remote-only).
        val needsPush = PendingPushes.all(appContext) + (local.keys - remoteTimestamps.keys)
        if (needsPush.isNotEmpty()) {
            for (entry in entryDao.getAllOnce()) {
                if (entry.uuid in needsPush) {
                    pushTracked(entry)
                }
            }
            // Pending markers whose entry is gone locally can never be drained — drop them,
            // or the indicator sticks at a count the user can do nothing about.
            for (uuid in PendingPushes.all(appContext) - local.keys) {
                PendingPushes.clear(appContext, uuid)
            }
        }

        // In both, remote newer -> defensive last-write-wins pull.
        for ((uuid, fields) in remote) {
            val localTs = local[uuid] ?: continue
            val remoteTs = remoteTimestamps[uuid] ?: 0L
            if (remoteTs > localTs) {
                entryDao.upsert(entryFromFields(uuid, fields))
                CloudSyncRepository.downloadImage(uuid, imageFile(uuid))
            }
        }

        // Catch entries whose doc pushed but whose image push failed (equal timestamps, so the
        // branches above never touch them). Re-push any local image missing from Storage.
        val remoteImages = CloudSyncRepository.fetchRemoteImageUuids()
        if (remoteImages != null) {
            for (entry in entryDao.getAllOnce()) {
                val file = imageFile(entry.uuid)
                if (file.exists() && entry.uuid !in remoteImages) {
                    CloudSyncRepository.pushImage(entry.uuid, file)
                }
            }
        }
    }

    private fun entryFromFields(uuid: String, fields: Map<String, Any?>): Entry = Entry(
        id = 0, // autogenerated; uuid unique index makes upsert idempotent
        name = fields["name"] as? String ?: "",
        bwhere = fields["bwhere"] as? String ?: "",
        kind = fields["kind"] as? String ?: "",
        date = fields["date"] as? String ?: "",
        notes = fields["notes"] as? String ?: "",
        pic = 0,
        uuid = uuid,
        updatedAt = fields["updatedAt"] as? Long ?: 0L
    )

    // ---- Initial-sync gate (prevents an interrupted restore from looking like mass deletion) ----

    private fun prefs() =
        appContext.getSharedPreferences("cloud_sync_prefs", Context.MODE_PRIVATE)

    private fun flagKey(): String? {
        val uid = FirebaseAuth.getInstance().currentUser?.uid ?: return null
        return "initial_sync_done_$uid"
    }

    private fun markInitialSyncDone() {
        val key = flagKey() ?: return
        prefs().edit().putBoolean(key, true).apply()
    }

    private fun isInitialSyncDone(): Boolean {
        val key = flagKey() ?: return false
        return prefs().getBoolean(key, false)
    }
}
